#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.3.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - ps: |
        Write-Verbose -Message ('APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME: {0}' -f $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME) -Verbose
        Write-Verbose -Message ('APPVEYOR_PULL_REQUEST_HEAD_COMMIT: {0}' -f $env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT) -Verbose
        Write-Verbose -Message ('APPVEYOR_REPO_COMMIT: {0}' -f $env:APPVEYOR_REPO_COMMIT) -Verbose
        Write-Verbose -Message ('APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH: {0}' -f $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) -Verbose
        Write-Verbose -Message ('APPVEYOR_ACCOUNT_NAME: {0}' -f $env:APPVEYOR_ACCOUNT_NAME) -Verbose
        Write-Verbose -Message ('APPVEYOR_PROJECT_NAME: {0}' -f $env:APPVEYOR_PROJECT_NAME) -Verbose
        Write-Verbose -Message ('APPVEYOR_REPO_NAME : {0}' -f $env:APPVEYOR_REPO_NAME ) -Verbose
        Write-Verbose -Message ('APPVEYOR_REPO_BRANCH: {0}' -f $env:APPVEYOR_REPO_BRANCH) -Verbose
        Write-Verbose -Message ('APPVEYOR_PROJECT_NAME: {0}' -f $env:APPVEYOR_PROJECT_NAME) -Verbose
        Write-Verbose -Message ('APPVEYOR_PROJECT_NAME: {0}' -f $env:APPVEYOR_PROJECT_NAME) -Verbose


        $moduleName = 'CertificateDsc'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -CodeCoverage `
            -CodeCovIo

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -ResourceModuleName $moduleName

        Invoke-AppVeyorDeployTask `
            -OptIn @()
