#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.3.{build}.0
install:
    - git clone https://github.com/regedit32/DscResource.Tests
    - ps: Push-Location
    - ps: cd "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests"
    - git checkout issue#265
    - ps: Pop-Location
    - ps: |
        $moduleName = 'CertificateDsc'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -CodeCoverage `
            -CodeCovIo `
            -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -ResourceModuleName $moduleName

        Invoke-AppVeyorDeployTask `
            -OptIn @()
